### ISSUE TITLE
chore: upgrade functionality checklist

### ISSUE THREAD

**Issue by ryuever** [red-armor/infinite-list#49]
- [ ] Viewable.Touchability viewability support
- [ ] ensure item meta state add listener should be triggered properly
- [ ] canIUseRIC should be a module..
